### PR TITLE
Added a Favicon to the Website

### PR DESCRIPTION
**Pull request by KanishkDadhich**
Hey @Shoray2002 .
I've solved the issue no #12 
I've added a nice favicon to this website.

Changes made :-
Added a new file - Favicon.png in the root directory
Edited an existing file - index.html

Thanks :)

### CODE REVIEW

**Comment by Shoray2002** [comment]
The image is a little informal 
Could you find something more formal

**Comment by Shoray2002** [comment]
An emoji might work

**Comment by KanishkDadhich** [comment]
Sure.

**Comment by KanishkDadhich** [comment]
Hey @Shoray2002 . I've changed the favicon to a bit more formal one. (FIXES #12 )
Please refer.
Thanks:)

**Pull request merged**
